### ISSUE TITLE
design bug

### ISSUE THREAD

**Issue by thefass** [PatristicTextArchive/pta_data#1]
Das Menu links schiebt sich über den Text, sowohl bei geöffneter als auch bei geschlossener Sidebar des Browsersv(Firefox 81.0.1)
https://pta.bbaw.de/pta/project/documentation

![Bildschirmfoto 2020-10-05 um 20 06 53](https://user-images.githubusercontent.com/14169098/95115956-9727b880-0746-11eb-998f-5de6a3bc7e2b.png)

**Comment by pharos-alexandria** [comment]
Danke! Ist ans interne frontend repository weitergeleitet.

**Comment by pharos-alexandria** [comment]
Closed in develop
