### ISSUE TITLE
data/pta0004/pta001/pta0004.pta001.pta-grcBibex.xml (v 40ae3150) - Lemma in Zeile 5809

### ISSUE THREAD

**Issue by jan-koester** [PatristicTextArchive/pta_data#5]
Theodoretus, Interpretatio in Danielem

https://pta.bbaw.de/api/pta/urn-cts-pta-pta0004.pta001.pta-grcBibex?output=xml. in Zeile 5809:  
`<lem wit="A B M P F E I W">ἀβδεναγώ.</lem>`

Ich vermute mal, der Punkt sollte außerhalb des Lemma-Elements stehen oder es muss in der Darstellung auf pta.bbaw.de angepasst werden, da dort das Personen-Lemma sowohl in der Liste als auch in der Annotation mit Punkt ausgegeben wird, was ich so sonst noch nicht auf pta.bbaw.de gesehen habe.

Nachtrag: ähnlicher Fall in 7365:  
`<lem wit="A M V P F B E W">ὁ δανιὴλ,</lem>`

**Comment by pharos-alexandria** [comment]
Ja, die Interpunktion sollte immer außerhalb stehen.

**Comment by pharos-alexandria** [comment]
done in inprogress
