### ISSUE TITLE
data/pta0004/pta001/pta0004.pta001.pta-grcBibex.xml (v 40ae3150) - mutmaßlich korrupte Bibelreferenzen

### ISSUE THREAD

**Issue by jan-koester** [PatristicTextArchive/pta_data#6]
Theodoretus, Interpretatio in Danielem

Das XML enthält min. 4 mutmaßlich korrupte Verweise auf Bibelstellen:
Zeile 1396: LX:Dn:4:8
Zeile 6323: LXX:Gen:39:2
Zeile 17033: LXX:2:39
Zeile 20288: LXX_Ex:22:28

Es können noch mehr sein, aber die sind mir eben beim Parsing aufgefallen.

**Comment by pharos-alexandria** [comment]
done in inprogress
