### ISSUE TITLE
pta_data/data/pta0004/pta001/pta0004.pta001.pta-MsI.xml Transkriptionsfehler

### ISSUE THREAD

**Issue by Ber-5** [PatristicTextArchive/pta_data#7]
Hallo,

in Datei pta_data/data/pta0004/pta001/pta0004.pta001.pta-MsI.xml

müsste in Zeile 95 θεοδωρίτου statt θεορωρίτου stehen.

**Comment by pharos-alexandria** [comment]
fixed
