### ISSUE TITLE
Theodoret-Edition läßt sich nicht öffnen

### ISSUE THREAD

**Issue by baem2** [PatristicTextArchive/pta_data#8]
Hallo,

wenn ich diese Seite lade:
https://pta.bbaw.de/pta/reader?left=urn-cts-pta-pta0004.pta001.pta-grcBibex&right=notext
... friert Chromium ein, Firefox schafft es nach einigem Rechnen (wird wohl an den zahlreichen Varianten liegen ...).

Die einzelnen Handschriften laufen problemlos in beiden Browsern.

Wahrscheinlich ist das Problem ohnehin schon bekannt, ich wollte es trotzdem gesagt haben.

**Comment by pharos-alexandria** [comment]
Herzlichen Dank! Ja, ist bekannt – und in der Development-Version auch schon behoben.
