### ISSUE TITLE
Urkunde 7, Euseb an Alexander

### ISSUE THREAD

**Issue by baem2** [PatristicTextArchive/pta_data#9]
Liebe Annette,

in unserem UE Digi-Kurs haben wir beim TEI-XML-lernen einen kleinen Fehler in Urkunde 7 gefunden (https://github.com/PatristicTextArchive/pta_data/commit/effd7e7b49ffc7cbc81e1b0efdcea0fa3c89b8dc): Im 5. Abschnitt müßte statt

``
<persName>Ἀλέξανδρον·</persName>
``
besser
``
<persName>Ἀλέξανδρον</persName>·
``
stehen.

(Sorry für diese ausführliche issue zu einem so minimalen Problem, aber wir lernen gleichzeitig bug tracking ...)

Schöne Grüße,
Ph & Co.

**Comment by pharos-alexandria** [comment]
Danke, @baem2!
